### ISSUE TITLE
Discord Link Broken

### ISSUE THREAD

**Issue by ghousetazeem** [Youth-Icon/.github#13]
The link for discord community is broken. Also the link [hellofaizan.me](https://hellofaizan.me) is also broken. Fix this so that I can join the discord community.

**Comment by Bashamega** [comment]
Hello:)

This is the new link: https://discord.gg/36s2k6kpRU

**Comment by hellofaizan** [comment]
@ghousetazeem Sorry, a lot of links are broken, will fix them sooner or later ✨

**Comment by hellofaizan** [comment]
> The link for discord community is broken. Also the link [hellofaizan.me](https://hellofaizan.me) is also broken. Fix this so that I can join the discord community.

use hellofaizan.tech or v2.hellofaizan.tech instead of hellofaizan.me, .me got expired
